### ISSUE TITLE
ClassNotFoundException: com.google.common.net.MediaType

### ISSUE THREAD

**Issue by vlatek** [timboudreau/acteur#3]
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/net/MediaType
	at com.mastfrog.acteur.headers.MediaTypeHeader.<init>(MediaTypeHeader.java:38)
	at com.mastfrog.acteur.headers.Headers.<clinit>(Headers.java:70)
	at com.mastfrog.netty.http.client.RequestBuilder.build(RequestBuilder.java:191)
	at com.mastfrog.netty.http.client.HttpClient$RB.execute(HttpClient.java:383)

acteur-headers-1.4.8

**Comment by suneeshkrishnath** [comment]
Thank you vlatek
